---

# Version of the Docker image for woken to use
woken_version: latest

# Id of woken in Marathon
woken_marathon_id: /algorithm-factory/woken

# Location of the configuration directory
woken_config_dir: /srv/docker/woken/config

# Logging level: DEBUG, INFO, WARNING, ERROR
woken_log_level: INFO

woken_host: "{{ ansible_fqdn }}"
# Port to use to expose woken to other services in the cluster.
woken_http_port: 31087
# Listen address for the web services
woken_http_network_interface: '0.0.0.0'
# Port used by Akka cluster
woken_akka_port: 31088
# Name of the Akka cluster setup by Woken
woken_akka_cluster: "woken"
# Amount of CPU reserved for woken
woken_cpus: 0.5
# Amount of memory in mb reserved for woken
woken_mem: 1024.0
# Name of the bridge network to connect to. Used also for the communication of Docker algorithms launched via Chronos
woken_docker_bridge_network: 'bridge'
# Additional parameters for Docker
woken_docker_parameters: []
woken_docker_image_basename: hbpmip/woken
woken_docker_image: "{{ woken_docker_image_basename }}:{{ woken_version }}"

# Attach the woken application to a particular host. The hostname should be the name known by Marathon / Mesos
woken_marathon_host: "{{ ansible_fqdn }}"
# Set of constraints to use to place woken on some particular host(s)
woken_marathon_constraints: [["hostname", "CLUSTER", "{{ woken_marathon_host | trim }}"]]

woken_mining_limit: 5
woken_experiment_limit: 5

woken_basicauth_username: admin
woken_basicauth_password: "WoKeN"

# How woken connects to the woken database storing its results
woken_db_port: 31432
woken_db_host: localhost
woken_db_user: postgres
woken_db_password: postgres
woken_db_name: woken
woken_db_jdbc_url: "jdbc:postgresql://{{ woken_db_host }}:{{ woken_db_port }}/{{ woken_db_name }}"
woken_db_jdbc_driver: "org.postgresql.Driver"
woken_db_jdbc_jar: "/usr/lib/R/libraries/postgresql-9.4-1201.jdbc41.jar"
woken_db_marathon_id: /algorithm-factory/wokendb

woken_result_db_port: '{{ woken_db_port }}'
woken_result_db_host: '{{ woken_db_host }}'
woken_result_db_user: '{{ woken_db_user }}'
woken_result_db_name: '{{ woken_db_name }}'
woken_result_db_password: '{{ woken_db_password }}'
woken_result_db_jdbc_url: '{{ woken_db_jdbc_url }}'
woken_result_db_jdbc_driver: '{{ woken_db_jdbc_driver }}'
woken_result_db_jdbc_jar: '{{ woken_db_jdbc_jar }}'

# How woken connects to the LDSM database containing the data to process
woken_features_db_port: '{{ ldsm_db_port }}'
woken_features_db_host: '{{ ldsm_db_host }}'
woken_features_db_user: '{{ ldsm_db_user }}'
woken_features_db_name: '{{ ldsm_db_name }}'
woken_features_db_password: '{{ ldsm_db_password }}'
woken_features_db_jdbc_url: '{{ ldsm_db_jdbc_url }}'
woken_features_db_jdbc_driver: '{{ ldsm_db_jdbc_driver }}'
woken_features_db_jdbc_jar: '{{ ldsm_db_jdbc_jar }}'

woken_metadata_db_port: '{{ meta_db_port }}'
woken_metadata_db_host: '{{ meta_db_host }}'
woken_metadata_db_user: '{{ meta_db_user }}'
woken_metadata_db_name: '{{ meta_db_name }}'
woken_metadata_db_password: '{{ meta_db_password }}'
woken_metadata_db_jdbc_url: '{{ meta_db_jdbc_url }}'
woken_metadata_db_jdbc_driver: '{{ meta_db_jdbc_driver }}'
woken_metadata_db_jdbc_jar: '{{ meta_db_jdbc_jar }}'

# URL to Chronos internal to the current cluster. You need to ensure that the woken application can reach that URL.
internal_chronos_url: http://default:4400
chronos_marathon_id: /algorithm-factory/chronos

# URL to Marathon master internal to the current cluster. You need to ensure that Ansible can reach that URL.
internal_marathon_url: "http://{{ marathon_hostname }}:{{ marathon_port }}"

woken_dependencies:
  - '{{ chronos_marathon_id }}'
  - '{{ woken_db_marathon_id }}'

# Roles are mip_node or mip_federation
woken_role: mip_node

woken_min_nr_of_members: 1
woken_validation_min_nr_of_members: 0
woken_scoring_min_nr_of_members: 0

woken_datasets:
  - name: sample
    description: Sample data
    label: Sample data
    tables: ["sample_data"]
    anonymisationLevel: Anonymised
  - name: churn
    description: Customer churn
    label: Customer churn
    tables: ["churn"]
    anonymisationLevel: Anonymised
  - name: desd-synthdata
    label: Synthetic data A
    description: Synthetic data A
    tables: ["cde_features_a"]
    anonymisationLevel: Anonymised

woken_env:
  CLUSTER_PORT: "{{ woken_akka_port }}"
  CLUSTER_IP: "{{ woken_host }}"
  WOKEN_PORT_8088_TCP_ADDR: "{{ woken_host }}"
  WOKEN_PORT_8088_TCP_PORT: "{{ woken_akka_port }}"
  DOCKER_BRIDGE_NETWORK: "{{ woken_docker_bridge_network }}"
  LOG_LEVEL: DEBUG
  KAMON_ENABLED: "no"
  ZIPKIN_ENABLED: "no"
  PROMETHEUS_ENABLED: "no"
  SIGAR_SYSTEM_METRICS: "no"
  JVM_SYSTEM_METRICS: "no"

woken_features_table: '{{ features_table }}'
woken_algorithms:
  - name: histograms
    docker_image: "hbpmip/python-histograms:latest"
    predictive: false
  - name: statisticsSummary
    docker_image: "hbpmip/r-summary-stats:latest"
    predictive: false
  - name: linearRegression
    docker_image: "hbpmip/r-linear-regression:latest"
    predictive: false
  - name: anova
    docker_image: "hbpmip/r-linear-regression:latest"
    predictive: false
  - name: knn
    docker_image: "hbpmip/java-rapidminer-knn:latest"
    predictive: true
  - name: naiveBayes
    docker_image: "hbpmip/java-rapidminer-naivebayes:latest"
    predictive: true
