---

- hosts: research-db
  become: yes
  gather_facts: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"
    - "{{ play_dir }}/vars/reference/endpoints.yml"
    - "{{ play_dir }}/vars/reference/research-database.yml"

  pre_tasks:

  - name: Need to add pre-defined research datasets?
    set_fact:
      research_add_predefined_datasets: "{{ setup_research_datasets is defined and setup_research_datasets != '' and features_from == 'research-db' }}"
    tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

  - name: Setup predefined research datasets
    include_vars: "{{ play_dir }}/vars/reference/{{ setup_research_datasets }}-research-datasets.yml"
    when: research_add_predefined_datasets
    tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

  - name: Add predefined data to research setup
    set_fact:
      research_db_docker_setup: "{{ predefined_research_db_docker_setup | union(research_db_docker_setup | default([])) }}"
    when: research_add_predefined_datasets
    tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

  roles:

    - role: research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']

    - role: audit-deployment
      installed_component: reference-research-database
      tags: ['research-database', 'research-db', 'database', 'reference', 'marathon-app']
