---

# Version of the Docker image for Portal frontend to use
portal_frontend_version: latest

# Id of Portal frontend in Marathon
portal_frontend_marathon_id: /web-analytics/portal-frontend

# Attach Portal frontend to a particular host. The hostname should be the name known by Marathon / Mesos
portal_frontend_marathon_host: '{{ ansible_fqdn }}'
# Set of constraints to use to place Portal frontend on some particular host(s)
portal_frontend_marathon_constraints: [["hostname", "CLUSTER", "{{ portal_frontend_marathon_host | trim }}"]]
# Number of instances of Portal frontend to launch
portal_frontend_instances: 1

# Amount of CPU reserved for Portal frontend
portal_frontend_cpus: 1.0
# Amount of memory in mb reserved for Portal frontend
portal_frontend_mem: 10.0

# Additional parameters for Docker
portal_frontend_docker_parameters: []

internal_portal_backend_server: 'localhost:4080'
portal_frontend_port: 80
portal_frontend_virtual_host: '{{ ansible_fqdn }}'
portal_frontend_error_log_level: 'warn'
portal_backend_context_path: ''

# Enable Google Analytics
portal_frontend_google_analytics: false
portal_frontend_google_tracker_id: 'UA-FILL-ME'

portal_frontend_env:
  WORKER_PROCESSES: "{{ [ 1, (portal_frontend_cpus | round | int)] | max }}"
  ERROR_LOG_LEVEL: '{{ portal_frontend_error_log_level }}'
  USE_GZIP: 'false'
  PORTAL_PORT: '8080'
  PORTAL_VIRTUAL_HOST: '{{ portal_frontend_virtual_host }}'
  PORTAL_BACKEND_SERVER: '{{ internal_portal_backend_server }}'
  PORTAL_BACKEND_CONTEXT: '{{ portal_backend_context_path }}'
  ANALYTICS: '{{ portal_frontend_google_analytics }}'
  TRACKER_ID: '{{ portal_frontend_google_tracker_id }}'
  MIP_VERSION: '{{ mip_version }}'
