---
- hosts: localhost
  gather_facts: no
  tasks:

    # Change concurrently with the required ansible version in requirements.txt
    - name: check for compatible Ansible version
      when: >
        ansible_version["string"] | version_compare("2.2", "<")
        or ansible_version["string"] | version_compare("2.4", ">=")
      fail:
        msg: >
          Your version of Ansible doesn't match the required version. Please
          install ansible-playbook with `pip install -r requirements.txt`.
      tags: ['checks', 'infra', 'infrastructure']

- hosts: all
  gather_facts: yes
  tasks:
    - name: check for accurate date
      when: (ansible_date_time['year'] | int) < 2017
      fail:
        msg: >
          Your machines have a misconfigured date. Please run
          `ansible --become all -a 'date --set="yyyymmdd"'` with the current
          date before continuing.
      tags: ['checks', 'infra', 'infrastructure']

    - name: check for compatible centos version
      when: ansible_os_family == 'RedHat' and ansible_distribution_version | version_compare("7.2", "<")
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of Centos.
          Please run the playbook playbooks/upgrade-packages.yml before
          continuing.
      tags: ['checks', 'infra', 'infrastructure']

    - name: check for compatible kernel version
      when: ansible_kernel | version_compare("3.10.0-327", "<")
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of the
          Linux kernel. Please run the playbook playbooks/upgrade-packages.yml
          before continuing.
      tags: ['checks', 'infra', 'infrastructure']
