---

#
# Setup mesos-leader on one or several servers.
# Requires: zookeeper installed on the same or some other servers.
#
# The following components are optional:
# * marathon: use --skip-tags=marathon
# * mesos-ui: use --skip-tags=mesos-ui
#

- hosts: mesos-leader
  become: yes
  vars_files:
    - "{{ play_dir }}/vars/common.yml"
    - "{{ play_dir }}/vars/versions.yml"
    - "{{ play_dir }}/vars/infrastructure/endpoints.yml"
    - "{{ play_dir }}/vars/infrastructure/zookeeper.yml"
    - "{{ play_dir }}/vars/infrastructure/mesos.yml"

  pre_tasks:

    - name: Set default value for skipped_roles
      set_fact:
        skipped_roles: []
      when: skipped_roles is not defined
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']

  roles:

    - role: mesos
      mesos_mode: "leader"
      mesos_leaders_group: "mesos-leader"
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']

    # Java 8 is required for Marathon
    - role: openjdk
      when: "'marathon' not in skipped_roles"
      tags: ['openjdk', 'marathon', 'mesos-frameworks', 'runtimes', 'infra', 'infrastructure']

    # TODO: should install only Marathon on 1 server, or deal with HA config for Marathon
    - role: marathon
      when: "'marathon' not in skipped_roles"
      tags: ['marathon', 'mesos-frameworks', 'runtimes', 'infra', 'infrastructure']

    #- role: mesos-ui
    #  tags: ['mesos-frameworks', 'mesos-ui']
    #  when: "'mesos-ui' not in skipped_roles"

    - role: audit-deployment
      installed_component: infrastructure-mesos-leader
      tags: ['mesos', 'container-platforms', 'infra', 'infrastructure']
