---

- include: check-requirements.yml

- include: cleanup.yml

- include: base-system.yml

- include: control-box.yml

# Mesos stack

- include: zookeeper.yml

- include: mesos-leader.yml

- include: mesos-mixed.yml

- include: mesos-follower.yml

- include: reverse-proxy.yml

# /Mesos stack
